name: Build

on: workflow_dispatch

jobs:
  
  build-android-armv7a:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build android-armv7a
      run: |
        scripts/build-android-armv7a.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
          name: Build
          path: /home/runner/work/Hls-android-test/Hls-android-test/build
        
